name: wbIdTest

on:
  push:
  schedule:    
    - cron:  '01,20 3,6 * * *'

jobs:
  wbTestEtf:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.x
      uses: actions/setup-python@v2
      with:
        # Python 版本的语义版本范围矩阵或准确的版本
        python-version: '3.x' 
        # 可选 - x64 或 x86 架构，默认为 x64
        architecture: 'x64' 
    - name: Install dependencies
      run: |
       python -m pip install requests
       python -m pip install pyquery
    # 您可以
    - name: Show wb id text
      run: |
       python wbTest.py
       python wbGsq.py
       python -c "print('successfull')"  
